version: "3"

services:
  app:
    container_name: weather_app
    environment:
      - APP_NAME=weather_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./docker:/docker
    env_file: "./docker/.env"
    depends_on:
      - db

  db:
    container_name: django_app_db
    image: postgres:14.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - /var/lib/django_app/postgresql:/var/lib/postgresql/data
      - /var/lib/django_app/db_backups:/backups
    ports:
      - "5432:5432"


volumes:
  my-datavolume:


